- name: Create Prometheus config directory
  file:
    path: /opt/prometheus
    state: directory

- name: Copy Prometheus config
  copy:
    src: "{{ playbook_dir }}/configs/prometheus.yml"
    dest: /opt/prometheus/prometheus.yml

- name: Run Prometheus container
  containers.podman.podman_container:
    name: prometheus
    image: quay.io/prometheus/prometheus
    state: started
    restart_policy: always
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z

