- name: Create Alertmanager directory
  file:
    path: /opt/alertmanager
    state: directory

- name: Copy Alertmanager config
  copy:
    src: "{{ playbook_dir }}/configs/alertmanager.yml"
    dest: /opt/alertmanager/alertmanager.yml

- name: Run Alertmanager container
  containers.podman.podman_container:
    name: alertmanager
    image: quay.io/prometheus/alertmanager
    state: started
    restart_policy: always
    ports:
      - "9093:9093"
    volumes:
      - /opt/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:Z

